# Generated by Django 2.2.1 on 2019-05-20 00:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_retrieved', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_id', models.CharField(max_length=256)),
                ('date_published', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('url', models.CharField(max_length=512)),
                ('content', models.TextField()),
            ],
        ),
    ]
